// // // console.log("hello js");
// // // // const a=12;
// // // var a=12;
// // // if(a>10){
// // //     // let b=5;
// // //     a=23;
// // //     console.log("a="+a);
// // // }
// // // console.log("hi, a="+a);
// // // // console.log("hi, a="+b);
// // // function fun(a,b,c=10){
// // //     console.log("Hello");
// // //     return a+b+c;
// // // }
// // // console.log(fun());
// // // console.log(fun(24,6));

// // // /*
// // // function cCompiler(){
// // //     return "C compiler";
// // // }
// // // function javaCompiler(){
// // //     return "Java Compiler";
// // // }
// // // function selectLanguage(clbk){
// // //     return "You have selected "+clbk();
// // // }
// // // const result=selectLanguage(javaCompiler);
// // // console.log(result)
// // // */

// // // function selectLanguage(language){
// // //     let data ;
// // //     if (language =="C"){
// // //         function cCompiler(){
// // //             return "C compiler";
// // //         }
// // //         data=cCompiler();
// // //     }
// // //     if(language =="java"){
// // //         function javaCompiler(){
// // //             return "Java Compiler";
// // //         }
// // //         data=javaCompiler();
// // //     }
// // //     return data;
// // // }
// // // const result=selectLanguage();
// // // console.log(result)
// // console.dir(document);
// // const div = document.getElementsByClassName("parent");
// // console.log(div);
// // div[0].innerHTML = "<h2 style=color:red> ABES Engineering colleuge</h2>";
// // const h1 = document.createElement("h1");
// // h1.innerText = "this is generated by dom";
// // h1.style.backgroundColor = "cyan";
// // console.log(h1);
// // div[0].appendChild(h1);
// // const img = document.createElement("img");
// // img.src = "./abes.png";
// // img.setAttribute("height", "200");
// // console.log(img);

// // div[0].appendChild(img);
// const btn = document.getElementById("btn");
// const disp = document.getElementById("disp");
// console.dir(disp);
// function getData() {
//   console.log("hello");
//   disp.innerHTML = "My name is aryan ";
// }
// btn.addEventListener("click", getData);
const promise = new promise((resolve, reject) => {
  let a = 12;
  if (a > 10) {
    resolve("Resolve");
  } else {
    reject("rejected");
  }
});
promise.then((msg) => console.log(msg)).catch((error) => console.log(error));
